version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: plant-pal
      POSTGRES_PASSWORD: plant-pal
      POSTGRES_DB: plant-pal
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
